---
title: "EDUC 641 Assignments"
site: distill::distill_website
output:
  html_document:
    toc: TRUE
    toc_depth: 2
    toc_float: TRUE
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. General Guidelines

The goal of the assignments is to practice the concepts and vocabulary we have been modeling in class and implement some of the techniques we have learned. You may work on your own or collaborate with one (1) or two partner(s). Please make sure that you engage in a full, fair and mutually-agreeable collaboration if you choose to collaborate. If you do collaborate, you should plan, execute and write-up your analyses together, not simply divide the work. Please make sure to indicate clearly when your work is joint and any other individual or resource (outside of class material) you consulted in your responses. Per the syllabus, please clearly state if you have relied on AI tools to generate your original text. You need not do so if you have used these tools only to help with coding tasks and/or light editing.

Each of the four assignments during the term is worth 15 points, and the final project is worth 30 points. Assignments are due at 11:59pm on their due date. If circumstances arise that require an extension on an assignment, please communicate with the lead instructor *prior* to the assignment's due date. We will publish the answer keys to assignments prior to class the following day; thus, late assignments will be penalized by two (2) points. While it is acceptable to consult the answer keys if you submit an assignment late, submissions that re-iterate word for word (or nearly so) the answer key will not be accepted. All late assignments must be turned in by the last day of classes. Late final projects may result in a final grade of I or D/F. Assignments scoring below a 13 may be revised and can receive a maximum score of up to 13.

# 2. Submission Requirements

Please upload below two files on Canvas:  

 * An .html, .doc/x, or .pdf file that includes your typed responses (in your own words and not identical to anybody else's), tables, and/or figures to the problems  
 * The .Rmd or .R file that you used to render the tables and figures in the above html/doc/pdf. 

# 3. Details about Assignments

## 3.1. Assignment 1

Categorical data 1: data structure and descriptives 

Objectives of this assignment

 * Describe and summarize categorical data

 * Create visualizations of categorical data

Deadline: October 10, 11:59pm

Download: [html file](./assignments/assignment01.html) | [cat.csv dataset](./data/cat.csv)

Key: 
<!-- [doc file](./assignments/keys/assignment01_key.docx); [R script](./assignments/keys/assignment01_key.R) -->

## 3.2. Assignment 2 

Categorical data 2: chi-square analysis

Objectives of this assignment

 * Describe relationships between categorical variables
 
 * Calculate an index of the strength of the relationship between two categorical variables, the chi-squared ($\chi^2$) statistic
 
 * Formulate and describe the purpose of a null hypothesis
 
 * Conceptually describe the criteria to make a statistical inference from a sample to a population
 
 * Interpret and report the results of a contingency-table analysis and a statistical inference from a chi-squared statistic

Deadline: October 19, 11:59pm

Download: [html file](./assignments/assignment02.html) | [cat.csv dataset](./data/cat.csv)

Key: 
<!-- [doc file](./assignments/keys/assignment02_key.docx); [R script](./assignments/keys/assignment02_key.R) -->

## 3.3. Assignment 3 

Continuous data 1: summarizing continuous data and $t$-tests

Objectives of this assignment

 * Describe and summarize continuous data

 * Create visualizations of continuous data
 
 * Conduct and interpret a one-sample $t$-test

Deadline: November 9, 9:00am

Download: [html file](./assignments/assignment03.html) | [cont.csv dataset](./data/cont.csv)

Key: 
<!-- [doc file](./assignments/keys/assignment03_key.docx); [R script](./assignments/keys/assignment03_key.R) -->

## 3.4. Assignment 4 

Continuous data 2: intro to bivariate regression

Deadline: November 29, 11:59pm

Download: [html file](./assignments/assignment04.html) | [cont.csv dataset](./data/cont.csv) 

Key: 
<!-- [doc file](./assignments/keys/assignment04_key.docx); [R script](./assignments/keys/assignment04_key.R) -->


## 3.5. Final

Final assignment 

Deadline: December 7, 11:59pm

Download: 
[html file](./assignments/assignment05.html) | [ah01.csv dataset](./data/ah01.csv); [ah02.csv dataset](./data/ah02.csv) 

Key:







